<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href='./failure_screenshots/search_09_11_2017_04_59_20.png'> <imgsrc='./failure_screenshots/search_09_11_2017_04_59_20.png' /> </a>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="55972" started-at="2017-11-09T11:28:27Z" finished-at="2017-11-09T11:29:23Z">
    <groups>
      <group name="loginlogout">
        <method signature="grofers.search()[pri:1, instance:kjc.grofers.webTests.grofers@9a7504c]" name="search" class="kjc.grofers.webTests.grofers"/>
      </group> <!-- loginlogout -->
    </groups>
    <test name="Default test" duration-ms="55972" started-at="2017-11-09T11:28:27Z" finished-at="2017-11-09T11:29:23Z">
      <class name="kjc.grofers.webTests.grofers">
        <test-method status="PASS" signature="openTheBrowser()[pri:0, instance:kjc.grofers.webTests.grofers@9a7504c]" name="openTheBrowser" is-config="true" duration-ms="29173" started-at="2017-11-09T16:58:27Z" finished-at="2017-11-09T16:58:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openTheBrowser -->
        <test-method status="FAIL" signature="search()[pri:1, instance:kjc.grofers.webTests.grofers@9a7504c]" name="search" duration-ms="24121" started-at="2017-11-09T16:58:56Z" finished-at="2017-11-09T16:59:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at kjc.grofers.webMethods.grofersMethods.appenddata(grofersMethods.java:67)
	at kjc.grofers.webTests.grofers.search(grofers.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method status="PASS" signature="catchExceptions(org.testng.ITestResult)[pri:0, instance:kjc.grofers.webTests.grofers@9a7504c]" name="catchExceptions" is-config="true" duration-ms="2643" started-at="2017-11-09T16:59:20Z" finished-at="2017-11-09T16:59:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=search status=FAILURE method=grofers.search()[pri:1, instance:kjc.grofers.webTests.grofers@9a7504c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='./failure_screenshots/search_09_11_2017_04_59_20.png'> <imgsrc='./failure_screenshots/search_09_11_2017_04_59_20.png' /> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- catchExceptions -->
      </class> <!-- kjc.grofers.webTests.grofers -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
